sudo: required

scala:
  - "2.11.8"

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      language: scala
      before_install:
        - bash bin/travis-linux.sh

    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install sbt
        - brew install bdw-gc
        - brew link bdw-gc
        - brew install jq
        - brew install re2

script:
- sbt tests/test
