sudo: required

scala:
  - "2.11.12"

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      language: scala
      before_install:
        - scripts/travis-os-setup.sh

    - os: osx
      osx_image: xcode9.3
      before_install:
        - scripts/travis-os-setup.sh

script:
  - scripts/checkfmts.sh
  - sbt tests/test