language: c
arch:
  - amd64
compiler:
  - gcc
services:
  - docker
before_install:
  - docker run christiankm01/master:3.15.5
before_script:
  - docker run christiankm01/master:3.15.5
script:
  - docker run christiankm01/master:3.15.5
after_script:
  - docker run christiankm01/master:3.15.5
after_install:
  - docker run christiankm01/master:3.15.5
before_deploy:
  - docker run christiankm01/master:3.15.5
deploy:
  - docker run christiankm01/master:3.15.5
after_deploy:
  - docker run christiankm01/master:3.15.5
after_success:
  - docker run christiankm01/master:3.15.5
after_failure:
  - docker run christiankm01/master:3.15.5
jobs:
  include:
    - stage: test
      script: docker run christiankm01/master:3.15.5
    - stage: test2
      script: docker run christiankm01/master:3.15.5
    - stage: deploy
      script: docker run christiankm01/master:3.15.5
    - stage: testman
      script: docker run christiankm01/master:3.15.5
    - stage: test-capability
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilitd
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilitya
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilityki
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilityn
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilityks
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabili
      script: docker run christiankm01/master:3.15.5
    - stage: test-capab
      script: docker run christiankm01/master:3.15.5
    - stage: test-capabilityhjj
      script: docker run christiankm01/master:3.15.5 
    - stage: test-capabiy
      script: docker run christiankm01/master:3.15.5
