sudo: required

scala:
  - "2.11.12"

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      language: scala
      before_install:
        - bash scripts/travis-linux.sh

    - os: osx
      osx_image: xcode8
      before_install:
        - brew update
        - brew install sbt
        - brew install re2

script:
  - java -version
  - if [ -n "$CLANG_FORMAT_PATH" ]; then bin/clangfmt --test; fi
  - scripts/scalafmt --test
  - sbt tests/test
