name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12]
        java: [ '11', '17' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '${{ matrix.java }}'
          cache: 'sbt'
      - name: Setup (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
            sudo apt-get update
            sudo apt-get install -y libatlas-base-dev
      - name: Run tests
        run: sbt +test
