name: CI

on:
  pull_request:
  push:
    branches: [ master main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libatlas-base-dev
    - name: Run tests
      run: sbt +test
