name: Scala CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcblas
    - name: Run tests
      run: sbt test
